package com.example.findword

object AppConstantes {
    const val DEFAULT_CHAR=' '
    const val DEFAULT_TEXT="please take a picture using the camera to start"
    const val MY_SPLITER="#"
    const val MAX_ROW=16
    const val MAX_COLUMN=31
    val STR_DICTIONARY= "the\n" +
            "of\n" +
            "and\n" +
            "to\n" +
            "a\n" +
            "in\n" +
            "for\n" +
            "is\n" +
            "on\n" +
            "that\n" +
            "by\n" +
            "this\n" +
            "with\n" +
            "i\n" +
            "you\n" +
            "it\n" +
            "not\n" +
            "or\n" +
            "be\n" +
            "are\n" +
            "from\n" +
            "at\n" +
            "as\n" +
            "your\n" +
            "all\n" +
            "have\n" +
            "new\n" +
            "more\n" +
            "an\n" +
            "was\n" +
            "we\n" +
            "will\n" +
            "home\n" +
            "can\n" +
            "us\n" +
            "about\n" +
            "if\n" +
            "page\n" +
            "my\n" +
            "has\n" +
            "search\n" +
            "free\n" +
            "but\n" +
            "our\n" +
            "one\n" +
            "other\n" +
            "do\n" +
            "no\n" +
            "information\n" +
            "time\n" +
            "they\n" +
            "site\n" +
            "he\n" +
            "up\n" +
            "may\n" +
            "what\n" +
            "which\n" +
            "their\n" +
            "news\n" +
            "out\n" +
            "use\n" +
            "any\n" +
            "there\n" +
            "see\n" +
            "only\n" +
            "so\n" +
            "his\n" +
            "when\n" +
            "contact\n" +
            "here\n" +
            "business\n" +
            "who\n" +
            "web\n" +
            "also\n" +
            "now\n" +
            "help\n" +
            "get\n" +
            "pm\n" +
            "view\n" +
            "online\n" +
            "c\n" +
            "e\n" +
            "first\n" +
            "am\n" +
            "been\n" +
            "would\n" +
            "how\n" +
            "were\n" +
            "me\n" +
            "s\n" +
            "services\n" +
            "some\n" +
            "these\n" +
            "click\n" +
            "its\n" +
            "like\n" +
            "service\n" +
            "x\n" +
            "than\n" +
            "find\n" +
            "price\n" +
            "date\n" +
            "back\n" +
            "top\n" +
            "people\n" +
            "had\n" +
            "list\n" +
            "name\n" +
            "just\n" +
            "over\n" +
            "state\n" +
            "year\n" +
            "day\n" +
            "into\n" +
            "email\n" +
            "two\n" +
            "health\n" +
            "n\n" +
            "world\n" +
            "re\n" +
            "next\n" +
            "used\n" +
            "go\n" +
            "b\n" +
            "work\n" +
            "last\n" +
            "most\n" +
            "products\n" +
            "music\n" +
            "buy\n" +
            "data\n" +
            "make\n" +
            "them\n" +
            "should\n" +
            "product\n" +
            "system\n" +
            "post\n" +
            "her\n" +
            "city\n" +
            "t\n" +
            "add\n" +
            "policy\n" +
            "number\n" +
            "such\n" +
            "please\n" +
            "available\n" +
            "copyright\n" +
            "support\n" +
            "message\n" +
            "after\n" +
            "best\n" +
            "software\n" +
            "then\n" +
            "jan\n" +
            "good\n" +
            "video\n" +
            "well\n" +
            "d\n" +
            "where\n" +
            "info\n" +
            "rights\n" +
            "public\n" +
            "books\n" +
            "high\n" +
            "school\n" +
            "through\n" +
            "m\n" +
            "each\n" +
            "links\n" +
            "she\n" +
            "review\n" +
            "years\n" +
            "order\n" +
            "very\n" +
            "privacy\n" +
            "book\n" +
            "items\n" +
            "company\n" +
            "r\n" +
            "read\n" +
            "group\n" +
            "sex\n" +
            "need\n" +
            "many\n" +
            "user\n" +
            "said\n" +
            "de\n" +
            "does\n" +
            "set\n" +
            "under\n" +
            "general\n" +
            "research\n" +
            "university\n" +
            "january\n" +
            "mail\n" +
            "full\n" +
            "map\n" +
            "reviews\n" +
            "program\n" +
            "life\n" +
            "know\n" +
            "games\n" +
            "way\n" +
            "days\n" +
            "management\n" +
            "p\n" +
            "part\n" +
            "could\n" +
            "great\n" +
            "united\n" +
            "hotel\n" +
            "real\n" +
            "f\n" +
            "item\n" +
            "international\n" +
            "center\n" +
            "ebay\n" +
            "must\n" +
            "store\n" +
            "travel\n" +
            "comments\n" +
            "made\n" +
            "development\n" +
            "report\n" +
            "off\n" +
            "member\n" +
            "details\n" +
            "line\n" +
            "terms\n" +
            "before\n" +
            "hotels\n" +
            "did\n" +
            "send\n" +
            "right\n" +
            "type\n" +
            "because\n" +
            "local\n" +
            "those\n" +
            "using\n" +
            "results\n" +
            "office\n" +
            "education\n" +
            "national\n" +
            "car\n" +
            "design\n" +
            "take\n" +
            "posted\n" +
            "internet\n" +
            "address\n" +
            "community\n" +
            "within\n" +
            "states\n" +
            "area\n" +
            "want\n" +
            "phone\n" +
            "dvd\n" +
            "shipping\n" +
            "reserved\n" +
            "subject\n" +
            "between\n" +
            "forum\n" +
            "family\n" +
            "l\n" +
            "long\n" +
            "based\n" +
            "w\n" +
            "code\n" +
            "show\n" +
            "o\n" +
            "even\n" +
            "black\n" +
            "check\n" +
            "special\n" +
            "prices\n" +
            "website\n" +
            "index\n" +
            "being\n" +
            "women\n" +
            "much\n" +
            "sign\n" +
            "file\n" +
            "link\n" +
            "open\n" +
            "today\n" +
            "technology\n" +
            "south\n" +
            "case\n" +
            "project\n" +
            "same\n" +
            "pages\n" +
            "uk\n" +
            "version\n" +
            "section\n" +
            "own\n" +
            "found\n" +
            "sports\n" +
            "house\n" +
            "related\n" +
            "security\n" +
            "both\n" +
            "g\n" +
            "county\n" +
            "american\n" +
            "photo\n" +
            "game\n" +
            "members\n" +
            "power\n" +
            "while\n" +
            "care\n" +
            "network\n" +
            "down\n" +
            "computer\n" +
            "systems\n" +
            "three\n" +
            "total\n" +
            "place\n" +
            "end\n" +
            "following\n" +
            "download\n" +
            "h\n" +
            "him\n" +
            "without\n" +
            "per\n" +
            "access\n" +
            "think\n" +
            "north\n" +
            "resources\n" +
            "current\n" +
            "posts\n" +
            "big\n" +
            "media\n" +
            "law\n" +
            "control\n" +
            "water\n" +
            "history\n" +
            "pictures\n" +
            "size\n" +
            "art\n" +
            "personal\n" +
            "since\n" +
            "including\n" +
            "guide\n" +
            "shop\n" +
            "directory\n" +
            "board\n" +
            "location\n" +
            "change\n" +
            "white\n" +
            "text\n" +
            "small\n" +
            "rating\n" +
            "rate\n" +
            "government\n" +
            "children\n" +
            "during\n" +
            "usa\n" +
            "return\n" +
            "students\n" +
            "v\n" +
            "shopping\n" +
            "account\n" +
            "times\n" +
            "sites\n" +
            "level\n" +
            "digital\n" +
            "profile\n" +
            "previous\n" +
            "form\n" +
            "events\n" +
            "love\n" +
            "old\n" +
            "john\n" +
            "main\n" +
            "call\n" +
            "hours\n" +
            "image\n" +
            "department\n" +
            "title\n" +
            "description\n" +
            "non\n" +
            "k\n" +
            "y\n" +
            "insurance\n" +
            "another\n" +
            "why\n" +
            "shall\n" +
            "property\n" +
            "class\n" +
            "cd\n" +
            "still\n" +
            "money\n" +
            "quality\n" +
            "every\n" +
            "listing\n" +
            "content\n" +
            "country\n" +
            "private\n" +
            "little\n" +
            "visit\n" +
            "save\n" +
            "tools\n" +
            "low\n" +
            "reply\n" +
            "customer\n" +
            "december\n" +
            "compare\n" +
            "movies\n" +
            "include"

}